/**
 * add_banner_text.mjs — composites the site masthead onto the header banner.
 *
 * WHY THIS EXISTS
 * The banner art itself is generated by NVIDIA Flux (see gen_images_nvidia.mjs) and is
 * deliberately TEXT-FREE: Flux renders lettering as garbled pseudo-text, so asking it for a
 * title produces nonsense. Instead the title is drawn here with ImageMagick, which renders
 * text exactly. The result is the classic GeoCities masthead: magenta Courier New with a
 * hard black outline and a black drop shadow, centred over the starfield.
 *
 * Requires ImageMagick on PATH (`magick`). Fonts are addressed by absolute path because
 * ImageMagick has no registered "Courier" family name and its argument parser eats
 * backslashes, so the path MUST use forward slashes.
 *
 * Usage: node scripts/add_banner_text.mjs
 */
import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';

const DOCS = path.join(process.cwd(), 'docs');
const BANNER = path.join(DOCS, 'images', 'banner-synthetic-gods.jpg');
const TMP = fs.mkdtempSync(path.join(process.cwd(), '.banner-text-'));
const FONT = 'C:/Windows/Fonts/courbd.ttf'; // Courier New Bold — forward slashes required
const TITLE = 'THE SYNTHETIC GODS';
const POINTSIZE = 36; // 18 chars x 0.6em x 36 = 388px = 83% of the 468px banner width

if (!fs.existsSync(BANNER)) {
  console.error(`ERROR: banner not found at ${BANNER}`);
  process.exit(1);
}

const magick = (args) => execFileSync('magick', args, { stdio: ['ignore', 'pipe', 'inherit'] });

// 1. Drop shadow — same glyphs, nudged down-right, pure black.
const shadow = path.join(TMP, 'shadow.png');
magick([
  '-size', '468x263', 'xc:none',
  '-font', FONT, '-pointsize', String(POINTSIZE),
  '-fill', 'black', '-stroke', 'black', '-strokewidth', '2',
  '-gravity', 'center',
  '-annotate', '+2+3', TITLE,
  shadow,
]);

// 2. Title layer — magenta fill with a hard black outline for legibility over the starfield.
const text = path.join(TMP, 'text.png');
magick([
  '-size', '468x263', 'xc:none',
  '-font', FONT, '-pointsize', String(POINTSIZE),
  '-fill', '#FF00FF', '-stroke', 'black', '-strokewidth', '2',
  '-gravity', 'center',
  '-annotate', '+0+0', TITLE,
  text,
]);

// 3. Composite over the banner, in place. Image size is preserved exactly.
magick([BANNER, shadow, '-composite', text, '-composite', '-quality', '90', '-strip', BANNER]);

fs.rmSync(TMP, { recursive: true, force: true });

const dims = magick(['identify', '-format', '%wx%h %b', BANNER]).toString().trim();
console.log(`✅ Banner masthead applied: "${TITLE}" — ${dims}`);